name: Call Api

on:
  release:
    types: [published]
  push:
    branches:
      - master
  schedule:
    - cron: "12 */3 * * *"
  watch:
    types: [started]

jobs:
  Task:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install requests
        run: |
          pip install requests
      - name: Read config from secrets
        env:
          CONFIG_ID: ${{ secrets.CONFIG_ID }}
          CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
        run: |
          cp main.py main2.py
          echo $CONFIG_ID > configid.txt
          echo $CONFIG_KEY > configkey.txt
          sed -i '10 r configid.txt' main2.py
          sed -i '12 r configkey.txt' main2.py
      - name: Test Api
        run: |
          echo `date + "%Y-%m-%d %H:%M:%S"` begin > time.log
          python main2.py
      - name: Delete secrets config #删除机密
        run: |
          rm -f main2.py
          rm -f configid.txt
          rm -f configkey.txt
      - name: Commit #上传新的refresh_token到仓库
        run: |
          git config --global user.email borber.drum@gmail.com
          git config --global user.name BORBER
          git add .
          git commit -m "update new refresh_token" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
